### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'attribute'

### ISSUE THREAD

**Issue by JabinHao** [mogroupumd/interface_stability#1]
## I met some errors when using the interface_stability:
 I have followed  the instructions and  installed the package successfully:
![install](https://user-images.githubusercontent.com/47690236/70408487-47735480-1a83-11ea-9c7b-f5b100f850e5.PNG)
 The phase_stability -h commmand could work 
![help](https://user-images.githubusercontent.com/47690236/70408353-d2a01a80-1a82-11ea-8fcf-dae02d15970a.PNG)
But when I try to use the sub-command, there are something wrong:
![error](https://user-images.githubusercontent.com/47690236/70408425-1430c580-1a83-11ea-98b2-60f6e2be8f72.PNG)
I tried to search this problem, but still cannot figure out how to solve it. Could you please explain why this is happening and what I can do to fix it? Thanks!

**Comment by adelaiden** [comment]
Yes, the problem is that the most recent version of pymatgen (2019.11.11 and newer) is incompatible with the VirtualEntry object (in this repository). The VirtualEntry property "attribute" was causing a conflict. That property is now removed from the latest version of this repository. If you download the newest version and reinstall setup.py, you should be able to run the code properly with no issues.

**Comment by JabinHao** [comment]
> Yes, the problem is that the most recent version of pymatgen (2019.11.11 and newer) is incompatible with the VirtualEntry object (in this repository). The VirtualEntry property "attribute" was causing a conflict. That property is now removed from the latest version of this repository. If you download the newest version and reinstall setup.py, you should be able to run the code properly with no issues.

I have installed the new version, it works now, thanks!
